# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea18174716dd899d681bbbd600caa74c36c982127874b79539d1ad3a95c349412306dd9246d922aa1b3488007b23ae2369ba32e02df52e241eb24ed3f1c6fd42

test:
  secret_key_base: e28018d2668ab83dae63e9c4707d5068b4fd12712be139ab9f8a31865efe731e9f605403e6448ac74fa363b28ea0d9ea7f7cddc642881fb900d963934bccc6a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
